github_ssh_credentials:
-
    id: 0e3c3056-e837-4586-b5c3-51301390e646
    username: vladkutas@gmail.com
    private_key: |
        -----BEGIN OPENSSH PRIVATE KEY-----
        b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
        QyNTUxOQAAACD2kgmlC4zk2cqKpO7VFj6C5hT3mvCaBqXxaj/lsif/0wAAAJi+9LouvvS6
        LgAAAAtzc2gtZWQyNTUxOQAAACD2kgmlC4zk2cqKpO7VFj6C5hT3mvCaBqXxaj/lsif/0w
        AAAEDVA5vSrgENsGpFbBtdQHcMzpNNTsv2pqdcDk2ZKwAobvaSCaULjOTZyoqk7tUWPoLm
        FPea8JoGpfFqP+WyJ//TAAAAE3ZsYWRrdXRhc0BnbWFpbC5jb20BAg==
        -----END OPENSSH PRIVATE KEY-----
    description: ssh key for https://github.com/VladislavKutas/jSudoku repo  
