---

- name: Provide libraries
  hosts: jenkins
  become: yes

  tasks: 

    - name: Create dependencies directory
      file:
        path: /var/lib/jenkins/libs
        state: directory
        owner: jenkins
        group: jenkins
        mode: 0700

    - name: Copy files reqired to source code analysis tools 
      copy: 
        src: "{{ item }}"
        dest: /var/lib/jenkins/libs/
        owner: jenkins
        group: jenkins
        mode: 0700
      with_items: ['dependencies/checkstyle', 'dependencies/pmd']
    
    - name: sds
      become: yes
      debug: "{{lookup('file', '/var/lib/jenkins/secrets/initialAdminPassword') }}"    